flash:
  notice: "alert-info"
  error: "alert-error"
  alert: "alert-warning"
  success: "alert-success"
  failed: "alert-danger"
validations:
  user:
    username:
      max_length: 30
      min_length: 5
  patient_record:
    first_name:
      max_length: 50
    last_name:
      max_length: 50
    address:
      max_length: 250
patient_records:
  per_page: 15
clinics:
  per_page: 10
users:
  per_page: 10
genders:
  - male
  - female
avatar:
  versions:
    medium: [200, 200]
    small: [100, 100]
image:
  versions:
    thumb: [400, 250]
logo:
  url: logo-vinalign.png
information:
  address: Ha Noi - Viet Nam
  phone_no: (+84) 0243 7552 999
  email: info@vinalign.com
  website: www.vinalign.com
