flash:
  notice: "alert-info"
  error: "alert-error"
  alert: "alert-warning"
  success: "alert-success"
  failed: "alert-danger"
validations:
  user:
    username:
      max_length: 30
      min_length: 6
