flash:
  notice: "alert-info"
  error: "alert-error"
  alert: "alert-warning"
  success: "alert-success"
  failed: "alert-danger"
validations:
  user:
    username:
      max_length: 30
      min_length: 5
  patient_record:
    first_name:
      max_length: 50
    last_name:
      max_length: 50
    address:
      max_length: 250
  expert:
    first_name:
      max_length: 50
    last_name:
      max_length: 50
    address:
      max_length: 250
    fakebook_url:
      max_length: 250
    title:
      max_length: 250
    workplace:
      max_length: 250
  article:
    title:
      max_length: 250
    summary:
      max_length: 2000
    content:
      max_length: 50000
    represent_image:
      max_size: 5.megabytes
patient_records:
  per_page: 15
clinics:
  per_page: 15
users:
  per_page: 10
experts:
  per_page: 10
  priorities: [1, 2, 3, 4, 5]
articles:
  per_page: 15
  per_page_front: 10
  related_on_page: 5
genders:
  - male
  - female
avatar:
  versions:
    medium: [200, 200]
    small: [100, 100]
preview_image:
  versions:
    thumb: [400, 200]
    big_thumb: [1200, 700]
image:
  versions:
    thumb: [400, 250]
logo:
  url: https://s3-ap-southeast-1.amazonaws.com/vinalign/logo.png
logo_square:
  url: https://s3-ap-southeast-1.amazonaws.com/vinalign/logo-square.png
information:
  address: Ha Noi - Viet Nam
  phone_no: (+84) 0243 7552 999
  email: info@vinalign.com
  website: www.vinalign.com
front:
  experts:
    per_page: 12
