flash:
  notice: "alert-info"
  error: "alert-error"
  alert: "alert-warning"
  success: "alert-success"
  failed: "alert-danger"
validations:
  user:
    username:
      max_length: 30
      min_length: 5
  patient_record:
    first_name:
      max_length: 50
    last_name:
      max_length: 50
    address:
      max_length: 250
  expert:
    first_name:
      max_length: 50
    last_name:
      max_length: 50
    address:
      max_length: 250
    fakebook_url:
      max_length: 250
    title:
      max_length: 250
    workplace:
      max_length: 250
  article:
    title:
      max_length: 250
    summary:
      max_length: 2000
    content:
      max_length: 50000
    represent_image:
      max_size: 5.megabytes
patient_records:
  per_page: 15
clinics:
  per_page: 15
users:
  per_page: 10
experts:
  per_page: 10
  priorities: [1, 2, 3, 4, 5]
articles:
  per_page: 15
  per_page_front: 10
  related_on_page: 5
notifications:
  on_dropdown_menu: 10
  per_page: 15
genders:
  - male
  - female
avatar:
  versions:
    medium: [150, 150]
    small: [50, 50]
preview_image:
  versions:
    thumb: [400, 200]
    big_thumb: [1200, 700]
image:
  versions:
    thumb: [400, 250]
    large: [1200, 750]
album:
  max_images: 14
software:
  url: https://s3-ap-southeast-1.amazonaws.com/vinalign/software/VINALIGN.ORTHO.STUDIO.VIEWER.Setup.x64.exe
logo:
  url: https://s3-ap-southeast-1.amazonaws.com/vinalign/logo.png
logo_square:
  url: https://s3-ap-southeast-1.amazonaws.com/vinalign/logo-square.png
information:
  address: Ha Noi - Viet Nam
  phone_no: 0243 7552 999
  email: info@vinalign.com
  website: www.vinalign.com
front:
  experts:
    per_page: 12
  carousel:
    news:
      limit: 5
meta_tag:
  google:
    description: "Chỉnh nha trong suốt Vinalign Việt Nam. Lần đầu tiên tại Việt Nam có một sản phẩm khay chỉnh nha trong suốt sử dụng công nghệ kỹ thuật số, hiện đại tiên tiến ra đời. Là sự tự hào của người Việt."
    keywords: [Nha khoa, chỉnh nha, vinalign, trong suốt, răng, chỉnh răng]
    copyright: "Công Ty TNHH Nghiên Cứu Ứng Dụng Nha Khoa Vinalign Việt Nam"
    application_name: "Vinalign"
  facebook:
    og_title: "Chỉnh nha trong suốt Vinalign Việt Nam"
    og_type: "website"
    og_image: http://vinalign.com/vinalign-square.png
    og_url: http://www.vinalign.com/
    og_description: "Chỉnh nha trong suốt Vinalign Việt Nam. Lần đầu tiên tại Việt Nam có một sản phẩm khay chỉnh nha trong suốt sử dụng công nghệ kỹ thuật số, hiện đại tiên tiến ra đời. Là sự tự hào của người Việt."
    fb_app_id: 638918379773409
